name: personal_mode_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  curved_navigation_bar: ^1.0.6
  hive: ^2.2.3
  http: ^1.4.0
  hive_flutter: ^1.1.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  device_preview: ^1.2.0
  awesome_notifications: ^0.10.1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.5.3
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/


  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Mulish-SemiBold.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf

